---
development:
  cloud_name: dakqk73zf
  api_key: '665459257779548'
  api_secret: wlZI4y4j2ywsV4OVDJVdWm5vTzA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dakqk73zf
  api_key: '665459257779548'
  api_secret: wlZI4y4j2ywsV4OVDJVdWm5vTzA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dakqk73zf
  api_key: '665459257779548'
  api_secret: wlZI4y4j2ywsV4OVDJVdWm5vTzA
  enhance_image_tag: true
  static_image_support: false
